
import __ASTRO_IMAGE_IMPORT_0 from "../images/debunking-devin.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2F4-debunking-devin.md";
import __ASTRO_IMAGE_IMPORT_1 from "../images/debunking-devin.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fes%2F4-debunking-devin.md";
import __ASTRO_IMAGE_IMPORT_2 from "../images/from-panic-to-production.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2F5-from-panic-to-production.md";
import __ASTRO_IMAGE_IMPORT_3 from "../images/from-panic-to-production.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fes%2F5-from-panic-to-production.md";
import __ASTRO_IMAGE_IMPORT_4 from "../images/laptop-workspace-unsplash.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2F1-reality-of-job-seeking.md";
import __ASTRO_IMAGE_IMPORT_5 from "../images/laptop-workspace-unsplash.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fes%2F1-reality-of-job-seeking.md";
import __ASTRO_IMAGE_IMPORT_6 from "../images/remote-work-tools.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2F2-remote-work-tools.md";
import __ASTRO_IMAGE_IMPORT_7 from "../images/remote-work-tools.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fes%2F2-remote-work-tools.md";
import __ASTRO_IMAGE_IMPORT_8 from "../images/rethinking-object-creation.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2F3-rethinking-object-creation.md";
import __ASTRO_IMAGE_IMPORT_9 from "../images/rethinking-object-creation.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fes%2F3-rethinking-object-creation.md";
export default new Map([["../images/debunking-devin.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2F4-debunking-devin.md", __ASTRO_IMAGE_IMPORT_0], ["../images/debunking-devin.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fes%2F4-debunking-devin.md", __ASTRO_IMAGE_IMPORT_1], ["../images/from-panic-to-production.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2F5-from-panic-to-production.md", __ASTRO_IMAGE_IMPORT_2], ["../images/from-panic-to-production.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fes%2F5-from-panic-to-production.md", __ASTRO_IMAGE_IMPORT_3], ["../images/laptop-workspace-unsplash.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2F1-reality-of-job-seeking.md", __ASTRO_IMAGE_IMPORT_4], ["../images/laptop-workspace-unsplash.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fes%2F1-reality-of-job-seeking.md", __ASTRO_IMAGE_IMPORT_5], ["../images/remote-work-tools.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2F2-remote-work-tools.md", __ASTRO_IMAGE_IMPORT_6], ["../images/remote-work-tools.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fes%2F2-remote-work-tools.md", __ASTRO_IMAGE_IMPORT_7], ["../images/rethinking-object-creation.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2F3-rethinking-object-creation.md", __ASTRO_IMAGE_IMPORT_8], ["../images/rethinking-object-creation.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fes%2F3-rethinking-object-creation.md", __ASTRO_IMAGE_IMPORT_9]]);
		